version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - node/install-packages
      - run:
        command: npm run test

workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git