version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@5.0.2

jobs:
  unit-test:
    executor:
      name: node/default
      tag: '16.15.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

workflows:
  heroku_deploy:
    jobs:
      - unit-test
      - heroku/deploy-via-git:
          requires:
            - unit-test # only run deploy-via-git job if the build job has completed