on:
  push:
    branches-ignore:
    - main
jobs:
  CI/CD Pipeline:
    name: CI/CD pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: build
        run: npm ci
        run: npm run build
      - name: unit-test
        needs: [build]
        run: npm run test
      - name: deploy
        needs: [build, unit-test]
        run: npm run prod