on:
  workflow_dispatch:
  push:
    branches-ignore:
    - main
jobs:
  pipeline:
    name: CI/CD pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stefanoeb/jest-action@1.0.3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Clean install packages
        run: npm ci
      # - name: Build
      #   run: npm run build
      - name: Unit-test
        run: npm run test
      - name: Deploy to render
        run: npm run prod